// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieScribe.Data;

#nullable disable

namespace MovieScribe.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230517171317_Five")]
    partial class Five
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieScribe.Models.ActorModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MovieScribe.Models.ActorsSUBMediaModel", b =>
                {
                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.HasKey("ActorID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("Actors_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.DistributorModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("MovieScribe.Models.GenreModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MovieScribe.Models.GenresSUBMediaModel", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.HasKey("GenreID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("Genres_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.LanguageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("MovieScribe.Models.LanguagesSUBMediaModel", b =>
                {
                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.HasKey("LanguageID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("Languages_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.MediaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("AiredDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Aired");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistributorID")
                        .HasColumnType("int");

                    b.Property<int>("ProducerID")
                        .HasColumnType("int");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<int>("StudioID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DistributorID");

                    b.HasIndex("ProducerID");

                    b.HasIndex("StudioID");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.ProducerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("MovieScribe.Models.StudioModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("MovieScribe.Models.WriterModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Writers");
                });

            modelBuilder.Entity("MovieScribe.Models.WritersSUBMediaModel", b =>
                {
                    b.Property<int>("WriterID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.HasKey("WriterID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("Writers_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.ActorsSUBMediaModel", b =>
                {
                    b.HasOne("MovieScribe.Models.ActorModel", "Actor")
                        .WithMany("Actor_SUB_Media")
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieScribe.Models.MediaModel", "Media")
                        .WithMany("Actor_SUB_Media")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.GenresSUBMediaModel", b =>
                {
                    b.HasOne("MovieScribe.Models.GenreModel", "Genre")
                        .WithMany("Genre_SUB_Media")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieScribe.Models.MediaModel", "Media")
                        .WithMany("Genre_SUB_Media")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.LanguagesSUBMediaModel", b =>
                {
                    b.HasOne("MovieScribe.Models.LanguageModel", "Language")
                        .WithMany("Language_SUB_Media")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieScribe.Models.MediaModel", "Media")
                        .WithMany("Language_SUB_Media")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.MediaModel", b =>
                {
                    b.HasOne("MovieScribe.Models.DistributorModel", "Distributor")
                        .WithMany("Media")
                        .HasForeignKey("DistributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieScribe.Models.ProducerModel", "Producer")
                        .WithMany("Media")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieScribe.Models.StudioModel", "Studio")
                        .WithMany("Media")
                        .HasForeignKey("StudioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("Producer");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("MovieScribe.Models.WritersSUBMediaModel", b =>
                {
                    b.HasOne("MovieScribe.Models.MediaModel", "Media")
                        .WithMany("Writer_SUB_Media")
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieScribe.Models.WriterModel", "Writer")
                        .WithMany("Writer_SUB_Media")
                        .HasForeignKey("WriterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("MovieScribe.Models.ActorModel", b =>
                {
                    b.Navigation("Actor_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.DistributorModel", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.GenreModel", b =>
                {
                    b.Navigation("Genre_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.LanguageModel", b =>
                {
                    b.Navigation("Language_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.MediaModel", b =>
                {
                    b.Navigation("Actor_SUB_Media");

                    b.Navigation("Genre_SUB_Media");

                    b.Navigation("Language_SUB_Media");

                    b.Navigation("Writer_SUB_Media");
                });

            modelBuilder.Entity("MovieScribe.Models.ProducerModel", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.StudioModel", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MovieScribe.Models.WriterModel", b =>
                {
                    b.Navigation("Writer_SUB_Media");
                });
#pragma warning restore 612, 618
        }
    }
}
